'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Swords,Sword,Shield,Heart,Zap,Coins,Gem,Bike,Dumbbell,Footprints,FlaskConical,Tent,Check,Lock,Plus,RefreshCw,Upload,ChevronRight,BookOpen,Volume2,VolumeX,CloudCheck,LoaderCircle,ArrowUpRight,Trophy,Sparkles,Unplug} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Progress} from '@/components/ui/progress';
import {Select,SelectTrigger,SelectContent,SelectItem,SelectValue} from '@/components/ui/select';
import {Button} from '@/components/ui/button';
import {newGame,heroPower,xpNeeded,ENEMIES,DAILY_XP_CAP,localDay,rewardPreview,activityLabel,activityKind,enemyIntent,type Mode,type GameState,type GameAction,type Attribute,type Activity,type Move} from '@/lib/game';
import {parseActivities} from '@/lib/import-activities';

type Snapshot={state:GameState;revision:number};
const spriteBoxes:Record<string,[number,number,number,number]>={hero:[102,85,332,339],slime:[651,209,224,192],mushroom:[1157,159,216,249],bat:[48,605,438,271],archer:[577,570,349,364],golem:[1036,512,460,434]};
let atlasPromise:Promise<HTMLImageElement>|null=null;
function atlas(assetBase:string){if(!atlasPromise)atlasPromise=new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>{atlasPromise=null;reject(new Error('image failed'));};img.src=assetBase+'/art/character-atlas.png';});return atlasPromise;}
function Sprite({name,className='',label,assetBase=''}:{name:string;className?:string;label?:string;assetBase?:string}){
 const ref=useRef<HTMLCanvasElement>(null);const [failed,setFailed]=useState(false);
 useEffect(()=>{let gone=false;atlas(assetBase).then(img=>{const c=ref.current;if(!c||gone)return;const [x,y,w,h]=spriteBoxes[name]||spriteBoxes.hero;c.width=w;c.height=h;const ctx=c.getContext('2d');if(!ctx)return;ctx.imageSmoothingEnabled=false;ctx.drawImage(img,x,y,w,h,0,0,w,h);const pixels=ctx.getImageData(0,0,w,h);for(let i=0;i<pixels.data.length;i+=4){const r=pixels.data[i],g=pixels.data[i+1],b=pixels.data[i+2];if(r>180&&b>180&&g<90)pixels.data[i+3]=0;}ctx.putImageData(pixels,0,0);}).catch(()=>setFailed(true));return()=>{gone=true;};},[name,assetBase]);
 return failed?<span className={`sprite-fallback ${className}`}>{label||name}</span>:<canvas ref={ref} className={`sprite ${className}`} role='img' aria-label={label||name}/>;
}
function ActivityIcon({type}:{type:string}){return activityKind(type)==='strength'?<Dumbbell/>:activityKind(type)==='explore'?<Footprints/>:<Bike/>;}
function prettyDate(start:string){return new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(start));}
function Meter({value,max,label,color='mint'}:{value:number;max:number;label:string;color?:string}){return <div className={`meter meter-${color}`}><div className='meter-label'><span>{label}</span><span>{value} <small>/ {max}</small></span></div><Progress value={Math.min(100,value/max*100)} aria-label={`${label} ${value}/${max}`}/></div>;}
export default function Game({request=fetch,assetBase='',cloudMode=false}:{request?:typeof fetch;assetBase?:string;cloudMode?:boolean}={}){
 const [mode,setMode]=useState<Mode>('demo');const [snapshot,setSnapshot]=useState<Snapshot>({state:newGame('demo'),revision:0});const [loaded,setLoaded]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [authNeeded,setAuthNeeded]=useState(false);const [selected,setSelected]=useState(0);const [syncOpen,setSyncOpen]=useState(false);const [helpOpen,setHelpOpen]=useState(false);const [recordsOpen,setRecordsOpen]=useState(false);const [apiKey,setApiKey]=useState('');const [syncError,setSyncError]=useState('');const [syncing,setSyncing]=useState(false);const [connected,setConnected]=useState(false);const [sound,setSound]=useState(false);const [hit,setHit]=useState(0);const [tab,setTab]=useState('adventure');const [importPreview,setImportPreview]=useState<ReturnType<typeof parseActivities>|null>(null);const [filename,setFilename]=useState('');
 const actionLock=useRef(false);const current=useRef(snapshot);const fileRef=useRef<HTMLInputElement>(null);const audioRef=useRef<AudioContext|null>(null);current.current=snapshot;
 const s=snapshot.state,p=heroPower(s),battle=s.battle,active=battle?.status==='active',enemyIndex=battle?.enemy??selected,enemy=ENEMIES[enemyIndex];const ready=loaded&&!busy&&!syncing;const unclaimed=s.records.filter(a=>!a.claimed);const todaysXP=s.records.filter(a=>a.claimed&&localDay(a.start)===localDay()).reduce((n,a)=>n+a.xp,0);
 const tone=useCallback((kind='click')=>{if(!sound)return;try{const context=audioRef.current??new AudioContext();audioRef.current=context;void context.resume();const oscillator=context.createOscillator(),gain=context.createGain();oscillator.type='triangle';oscillator.frequency.setValueAtTime(kind==='win'?660:kind==='heavy'?120:380,context.currentTime);oscillator.frequency.exponentialRampToValueAtTime(kind==='win'?990:90,context.currentTime+.14);gain.gain.setValueAtTime(.07,context.currentTime);gain.gain.exponentialRampToValueAtTime(.001,context.currentTime+.18);oscillator.connect(gain);gain.connect(context.destination);oscillator.start();oscillator.stop(context.currentTime+.19);}catch{/* Sound is optional. */}},[sound]);
 const loadGame=useCallback(async(m:Mode,signal?:AbortSignal)=>{setLoaded(false);setError('');setAuthNeeded(false);try{const response=await request(`/api/game?mode=${m}`,{cache:'no-store',signal});const data=await response.json();if(!response.ok){setAuthNeeded(response.status===401);throw new Error(data.error||'无法读取存档。');}if(!signal?.aborted){setSnapshot(data);setSelected(data.state.battle?.enemy??Math.min(data.state.cleared.length,5));setLoaded(true);}}catch(e){if(!signal?.aborted)setError(e instanceof Error?e.message:'网络暂时不可用。');}},[request]);
 useEffect(()=>{const controller=new AbortController();void loadGame(mode,controller.signal);return()=>controller.abort();},[mode,loadGame]);
 useEffect(()=>()=>{void audioRef.current?.close();},[]);
 const changeMode=(m:Mode)=>{if(actionLock.current||syncing)return;setSnapshot({state:newGame(m),revision:0});setLoaded(false);setMode(m);setSelected(0);setImportPreview(null);setError('');};
 const act=async(action:GameAction)=>{if(actionLock.current||!loaded||syncing)return false;actionLock.current=true;setBusy(true);setError('');try{const response=await request('/api/game',{method:'POST',headers:{'Content-Type':'application/json'},signal:AbortSignal.timeout(25000),body:JSON.stringify({mode,revision:current.current.revision,action})});const data=await response.json();if(data.state)setSnapshot(data);if(!response.ok)throw new Error(data.error||'操作未完成。');if(action.type==='move'){setHit(h=>h+1);tone(data.state.battle?.status==='won'?'win':action.move);}else tone();return true;}catch(e){setError(e instanceof Error?e.message:'连接中断，请重试。');return false;}finally{actionLock.current=false;setBusy(false);}};
 const connect=async()=>{if(syncing||actionLock.current||!loaded)return;setSyncError('');if(mode!=='real'){setSyncError('请先切换到真实冒险。');return;}setSyncing(true);actionLock.current=true;try{const response=await request('/api/intervals',{method:'POST',headers:{'Content-Type':'application/json'},signal:AbortSignal.timeout(25000),body:JSON.stringify({apiKey,revision:current.current.revision})});const data=await response.json();if(data.state)setSnapshot(data);if(!response.ok)throw new Error(data.error||'同步未完成。');setConnected(true);setSyncOpen(false);setError('');}catch(e){setConnected(false);setSyncError(e instanceof Error?e.message:'暂时无法同步。');}finally{setSyncing(false);actionLock.current=false;}};
 const readImport=async(file:File)=>{setSyncError('');setImportPreview(null);if(file.size>500000){setSyncError('请选择小于500 KB的CSV或JSON文件。');return;}if(!/\.(csv|json)$/i.test(file.name)){setSyncError('当前支持CSV或JSON运动记录。');return;}try{const records=parseActivities(await file.text(),file.name);if(!records.length)throw new Error('文件中没有运动记录。');setImportPreview(records);setFilename(file.name);}catch(e){setSyncError(e instanceof Error?e.message:'文件无法读取。');}};
 const confirmImport=async()=>{if(!importPreview)return;if(await act({type:'import',records:importPreview})){setImportPreview(null);setSyncOpen(false);}};
 const start=()=>{setTab('adventure');void act({type:'start',enemy:selected});};
 const onMove=(move:Move)=>void act({type:'move',move});
 const renderRecord=(a:Activity)=>{const reward=rewardPreview(s,a);return <div className={`activity-row ${a.claimed?'is-claimed':''}`} key={a.id}><span className={`activity-icon ${activityKind(a.type)}`}><ActivityIcon type={a.type}/></span><div className='activity-description'><div className='activity-title'>{a.name}</div><div className='activity-meta'>{activityLabel(a.type)} · {a.minutes} 分钟{a.source==='demo'?' · 演示':''}</div><div className='activity-date'>{prettyDate(a.start)}</div></div><div className='activity-reward'>{a.claimed?<span className='claimed'><Check size={14}/> 已领取</span>:<><strong>+{reward.xp}<small> EXP</small></strong><Button className='small-action' disabled={!ready||!!active} onClick={()=>void act({type:'claim',id:a.id})}>领取</Button></>}</div></div>;};
 return <div className='game-app'>
  <header className='topbar'><div className='brand'><span className='brand-mark'><Swords/></span><div><strong>现实练级</strong><small>REAL LEVELING</small></div><span className='edition'>序章</span></div><div className='topbar-actions'><span className='save-state'>{busy||syncing?<LoaderCircle className='spin'/>:<CloudCheck/>}{!loaded?'读取存档':busy||syncing?'正在保存':'进度已保存'}</span><button className='icon-button' aria-label={sound?'关闭音效':'开启音效'} title={sound?'关闭音效':'开启音效'} onClick={()=>setSound(v=>!v)}>{sound?<Volume2/>:<VolumeX/>}</button><button className='icon-button' aria-label='冒险手册' title='冒险手册' onClick={()=>setHelpOpen(true)}><BookOpen/></button></div></header>
  <div className='game-shell'>
   <div className='expedition-heading'><div><div className='eyebrow'>CHAPTER 01 <span>／</span> FOREST EXPEDITION</div><h1>林间远征<span>现实的每一步，都算数。</span></h1></div><div className='mode-picker'><Select value={mode} onValueChange={v=>changeMode(v as Mode)} disabled={busy||syncing}><SelectTrigger aria-label='冒险模式'><SelectValue/></SelectTrigger><SelectContent><SelectItem value='demo'>演示冒险</SelectItem><SelectItem value='real'>真实冒险</SelectItem></SelectContent></Select><Button className='sync-button' onClick={()=>{setSyncError('');setSyncOpen(true);}} disabled={busy||syncing}><RefreshCw size={16}/>同步运动</Button></div></div>
   {error&&<div className='error-banner' role='alert'><span>{error}</span>{authNeeded&&!cloudMode?<a href='/signin-with-chatgpt?return_to=%2F' target='_top'>登录并继续</a>:!loaded?<button onClick={()=>void loadGame(mode)}>重新读取</button>:<button onClick={()=>setError('')}>知道了</button>}</div>}
   <div className='adventure-layout'>
    <aside className='character-panel panel'>
     <div className='panel-heading'><span>你的冒险者</span><span className='tiny-tag'>{mode==='demo'?'演示角色':'真实角色'}</span></div>
     <div className='portrait'><div className='portrait-halo'/><Sprite assetBase={assetBase} name='hero' label='佩戴蓝色围巾的冒险者'/><span className='level-badge'>LV. {s.level.toString().padStart(2,'0')}</span></div>
     <div className='character-name'><h2>{s.cleared.includes(5)?'林间守护者':'初行者'}</h2><span>自由成长 · 冒险者</span></div>
     <Meter value={s.xp} max={xpNeeded(s.level)} label='升级经验' color='gold'/>
     <div className='attribute-heading'><span>角色属性</span><span className='point-tag'>{s.points} 点待分配</span></div>
     {([{key:'strength',name:'力量',icon:Sword,desc:'每点攻击 +2'},{key:'endurance',name:'耐力',icon:Heart,desc:'每点生命 +8'},{key:'agility',name:'敏捷',icon:Zap,desc:'每点暴击 +2%，上限40%'}] as const).map(a=><div className='attribute-row' key={a.key}><a.icon/><div><strong>{a.name}</strong><small>{a.desc}</small></div><b>{s.stats[a.key]}</b><button className='add-point' disabled={!ready||s.points<1||!!active} onClick={()=>void act({type:'allocate',stat:a.key as Attribute})} aria-label={`给${a.name}加1点`}><Plus/></button></div>)}
     <div className='combat-stats'><span>攻击 <b>{p.attack}</b></span><span>防御 <b>{p.defense}</b></span><span>暴击 <b>{p.crit}%</b></span></div>
     <div className='wallet'><span><Coins/> <b>{s.gold}</b><small>金币</small></span><span><Gem/> <b>{s.materials}</b><small>符石</small></span></div>
     <button className='camp-link' onClick={()=>void act({type:'rest'})} disabled={!ready||!!active}><Tent/><span>回营地补给<small>补满药水 · 休息不掉级</small></span><ChevronRight/></button>
    </aside>
    <main className='main-play'>
     <Tabs value={tab} onValueChange={setTab}><div className='play-heading'><TabsList variant='line'><TabsTrigger value='adventure'><Swords/>远征</TabsTrigger><TabsTrigger value='forge' disabled={!!active}><Gem/>装备工坊</TabsTrigger></TabsList><span className='zone-count'>{String(s.cleared.length).padStart(2,'0')} <span>/ 06 区域</span></span></div>
      <TabsContent value='adventure' className='play-content'>
       <section className={`battle-scene ${battle?.status==='won'?'victorious':''}`} aria-label='森林战斗场景'>
        <img className='forest-backdrop' src={assetBase+'/art/forest-battle.png'} alt='阳光穿过森林，古老遗迹伫立在苔石小径尽头'/><div className='scene-vignette'/>
        <div className='scene-top'><span className='zone-label'><span>{String(enemyIndex+1).padStart(2,'0')}</span>{enemy.area}</span><span className={`scene-state ${active?'combat':''}`}>{active?`第 ${battle.turn} 回合`:battle?.status==='won'?'区域已净化':battle?.status==='lost'?'休整后再出发':'等待出发'}</span></div>
        <div className='fighter-hud hero-hud'><div><span>初行者</span><b>LV.{s.level}</b></div><Meter value={battle?.hp??p.hp} max={p.hp} label='生命'/>{active&&<Meter value={battle.energy} max={p.energy} label='能量' color='blue'/>}</div>
        <div className='fighter-hud enemy-hud'><div><span>{enemy.name}</span><b>{enemy.trait}</b></div><Meter value={battle?.enemyHp??enemy.hp} max={enemy.hp} label='生命' color='red'/></div>
        <div key={`hero-${hit}`} className={`scene-hero ${active&&hit?'hero-strike':''}`}><Sprite assetBase={assetBase} name='hero' label='你的冒险者'/></div>
        <div key={`enemy-${hit}`} className={`scene-enemy ${enemy.sprite} ${enemyIndex===4?'amber-slime':''} ${battle?.status==='won'?'defeated':active&&hit?'enemy-hit':''}`}><Sprite assetBase={assetBase} name={enemy.sprite} label={enemy.name}/></div>
        {!battle&&<div className='scene-prompt'><span>你的下一场冒险</span><strong>{enemy.name}</strong></div>}
        {active&&<div className={`enemy-intent ${battle.turn%3===0&&enemyIndex>0?'warning':''}`}><Shield size={14}/>{enemyIntent(battle)}</div>}
        {battle&&battle.status!=='active'&&<div className='battle-result' role='status'>{battle.status==='won'?<Trophy/>:<Tent/>}<h2>{battle.status==='won'?(enemyIndex===5?'林间守护者，诞生！':'战斗胜利！'):'先休息，再出发'}</h2><p>{s.notice}</p><Button className='gold-button' onClick={()=>{if(battle.status==='won')setSelected(Math.min(enemyIndex+1,5));void act({type:'rest'});}} disabled={!ready}>{battle.status==='won'?'收好战利品':'回营地补给'}<ChevronRight size={16}/></Button></div>}
       </section>
       <div className='battle-controls'>
        {active?<div className='move-grid'><Button className='move-button primary-move' onClick={()=>onMove('attack')} disabled={!ready}><Sword/><span>攻击<small>恢复2能量</small></span><kbd>1</kbd></Button><Button className='move-button' onClick={()=>onMove('heavy')} disabled={!ready||battle.energy<4}><Zap/><span>重击<small>消耗4能量</small></span><kbd>2</kbd></Button><Button className='move-button' onClick={()=>onMove('guard')} disabled={!ready}><Shield/><span>防御<small>减伤 · 回能</small></span><kbd>3</kbd></Button><Button className='move-button' onClick={()=>onMove('potion')} disabled={!ready||s.potions<1||battle.hp===p.hp}><FlaskConical/><span>药水<small>剩余 {s.potions} 瓶</small></span><kbd>4</kbd></Button></div>:<div className='departure'><div><span className='ready-icon'><Swords/></span><span><strong>{s.cleared.includes(selected)?'再次挑战':'准备好出发了吗？'}</strong><small>{ENEMIES[selected].hint}</small></span></div><Button className='gold-button' disabled={!ready||!!battle} onClick={start}>{!loaded?'读取进度中…':'开始战斗'}<ChevronRight size={16}/></Button></div>}
        {active&&<div className='turn-footer'><span>你的回合 · 选择一个行动</span><button onClick={()=>void act({type:'leave'})} disabled={!ready}>撤回营地</button></div>}
       </div>
       <div className='adventure-map'><div className='section-label'><span>远征路线</span><span>通关解锁下一站</span></div><div className='zone-grid'>{ENEMIES.map((e,i)=>{const locked=i>0&&!s.cleared.includes(i-1);return <button key={e.name} disabled={locked||!!battle||!ready} className={`zone-card ${selected===i?'selected':''} ${s.cleared.includes(i)?'cleared':''}`} onClick={()=>setSelected(i)} aria-label={`${e.area}，${locked?'未解锁':s.cleared.includes(i)?'已通关':'可挑战'}`}><div className='zone-icon'>{locked?<Lock/>:s.cleared.includes(i)?<Check/>:i===5?<Trophy/>:<Swords/>}</div><small>{i===5?'首领':`0${i+1}`}</small><span>{e.area}</span></button>;})}</div></div>
       {battle&&<div className='battle-log'><span>战斗记录</span><p>{battle.log[0]}</p></div>}
      </TabsContent>
      <TabsContent value='forge'><section className='forge-panel panel'><div className='forge-title'><Gem/><div><div className='eyebrow'>EQUIPMENT WORKSHOP</div><h2>把每次积累，锻造成力量。</h2></div></div><div className='equipment-grid'>{(['weapon','armor'] as const).map(item=>{const cost=20+s[item]*15;const max=s[item]>=5;return <article className='equipment-card' key={item}><span className={`equipment-icon ${item}`}>{item==='weapon'?<Sword/>:<Shield/>}</span><span className='tiny-tag'>强化 +{s[item]}</span><h3>{item==='weapon'?'旅人短剑':'林行者护甲'}</h3><p>{item==='weapon'?`装备攻击 +${s.weapon*4}`:`装备防御 +${s.armor*3} · 生命 +${s.armor*9}`}</p><div className='upgrade-preview'>{max?'已达到本章强化上限':item==='weapon'?'下一级：攻击 +4':'下一级：防御 +3，生命 +9'}</div><Button className='sync-button' disabled={!ready||max||s.gold<cost||s.materials<2} onClick={()=>void act({type:'forge',item})}>{max?'已满级':<><Coins size={15}/>{cost}<Gem size={15}/>2 · 锻造</>}</Button></article>;})}</div><div className='forge-note'><Sparkles/><span>运动记录产出符石，首次通关获得金币与额外符石。装备强化永久保留。</span></div></section></TabsContent>
     </Tabs>
    </main>
    <aside className='activity-panel panel'><div className='panel-heading'><span>运动补给站</span><span className={`tiny-tag ${mode==='demo'?'demo-tag':''}`}>{mode==='demo'?'演示数据':s.syncSource||'尚未接入'}</span></div><div className='activity-intro'><span className='supply-icon'><Zap/></span><h2>让运动，成为经验。</h2><p>{mode==='demo'?'先领取一条演示记录，体验升级。':'同步自己的运动记录，领取成长奖励。'}</p></div><div className='daily-reward'><Meter value={todaysXP} max={DAILY_XP_CAP} label='今日已获经验' color='gold'/><span>150 是奖励上限，不是运动目标</span></div><div className='record-heading'><span>{mode==='demo'?'可体验的记录':'最近运动'}</span><span>{unclaimed.length} 条待领取</span></div><div className='activity-list'>{s.records.length?s.records.slice(0,3).map(renderRecord):<div className='records-empty'><Unplug/><strong>还没有运动记录</strong><p>连接 Intervals.icu，或导入自己的记录文件。</p><Button className='small-action' onClick={()=>setSyncOpen(true)}>连接运动数据</Button></div>}</div>{s.records.length>3&&<button className='all-records' onClick={()=>setRecordsOpen(true)}>查看全部 {s.records.length} 条记录<ChevronRight size={15}/></button>}<div className='supply-note'><Shield/><p>同一场运动只奖励一次。<br/>等级与装备不会因休息而降低。</p></div><button className='connection-link' onClick={()=>{setSyncError('');setSyncOpen(true);}}>{mode==='demo'?'用自己的运动开始冒险':connected?'同步近30天运动':'连接或导入运动'}<ArrowUpRight size={16}/></button></aside>
   </div>
   <div className='notice-strip' role='status' aria-live='polite'><span className='notice-icon'>{busy||syncing?<LoaderCircle className='spin'/>:<Sparkles/>}</span><p>{loaded?s.notice:'正在打开你的冒险存档…'}</p><span className='mode-caption'>{mode==='demo'?'演示进度与真实进度独立':'真实冒险 · 私人存档'}</span></div>
   <footer className='game-footer'><span>运动后，再来一场冒险。</span><button onClick={()=>setHelpOpen(true)}>玩法与奖励规则<BookOpen size={14}/></button></footer>
  </div>
  <Keyboard onMove={onMove} enabled={!!active&&ready&&!syncOpen&&!helpOpen&&!recordsOpen}/>
  <Dialog open={syncOpen} onOpenChange={v=>{if(!syncing)setSyncOpen(v);}}><DialogContent className='game-dialog sync-dialog'><DialogHeader><DialogTitle>连接你的现实冒险</DialogTitle><DialogDescription>仅保存运动类型、日期、时长和标题；路线和心率不写入游戏存档。真实记录保存在你的私人冒险中。</DialogDescription></DialogHeader>
   {mode==='demo'?<div className='demo-connect'><span className='big-symbol'><RefreshCw/></span><h3>准备好用自己的运动升级了吗？</h3><p>切换后会打开独立的真实存档。演示角色和奖励仍会保留。</p><Button className='sync-button' disabled={busy} onClick={()=>changeMode('real')}>切换到真实冒险<ChevronRight size={16}/></Button><small>没有运动账户也可以先使用文件导入。</small></div>:<Tabs defaultValue='connect' className='sync-tabs'><TabsList><TabsTrigger value='connect'>Intervals.icu</TabsTrigger><TabsTrigger value='import'>文件导入</TabsTrigger></TabsList><TabsContent value='connect'><div className='connection-status'><span>{connected?'本次会话已连接':'尚未连接账户'}</span>{s.lastSync&&<small>上次导入：{prettyDate(s.lastSync)}</small>}</div><p className='form-copy'>个人试用入口。在 Intervals.icu 设置底部的「Developer Settings」生成 API Key，然后同步近30天记录。</p><label className='form-label' htmlFor='api-key'>个人 API Key</label><input className='game-input' type='password' id='api-key' autoComplete='off' value={apiKey} onChange={e=>setApiKey(e.target.value)} placeholder='仅用于本次连接' disabled={syncing}/><p className='field-help'>密钥只在本页内存中临时使用，不写入存档；刷新页面后需重新填写。向更多客户开放前需改接平台授权登录。</p><div className='dialog-actions'><a href='https://intervals.icu/settings' target='_blank' rel='noreferrer'>打开平台设置<ArrowUpRight size={14}/></a><Button className='sync-button' disabled={!ready||!apiKey.trim()||!!active} onClick={()=>void connect()}>{syncing?<LoaderCircle className='spin'/>:<RefreshCw size={16}/>} {syncing?'正在读取运动…':'同步近30天'}</Button></div>{apiKey&&<button className='disconnect-button' disabled={syncing} onClick={()=>{setApiKey('');setConnected(false);}}>清除本次连接密钥</button>}</TabsContent><TabsContent value='import'><p className='form-copy'>支持 Intervals.icu 活动 CSV / JSON。CSV需包含 id、name、type、start_date_local、moving_time（秒）；也支持 start 和 minutes（分钟）。无时区日期按上海时间读取。</p><input type='file' ref={fileRef} className='sr-only' accept='.csv,.json' onChange={e=>{const file=e.target.files?.[0];if(file)void readImport(file);e.target.value='';}}/><button className='file-drop' onClick={()=>fileRef.current?.click()} disabled={!ready||!!active}><Upload/><strong>选择运动记录文件</strong><span>CSV / JSON · 最多250条 · 500 KB以内</span></button>{importPreview&&<div className='import-preview'><strong>{filename}</strong><span>识别到 {importPreview.length} 条记录</span><p>导入后可逐条领取，重复记录自动略过。</p><Button className='sync-button' disabled={!ready||!!active} onClick={()=>void confirmImport()}>确认导入 {importPreview.length} 条</Button></div>}</TabsContent></Tabs>}
   {(syncError||error)&&<div className='dialog-error' role='alert'>{syncError||error}</div>}{active&&mode==='real'&&<p className='field-help'>请先结束当前战斗，再导入运动记录。</p>}
  </DialogContent></Dialog>
  <Dialog open={helpOpen} onOpenChange={setHelpOpen}><DialogContent className='game-dialog help-dialog'><DialogHeader><DialogTitle>冒险手册</DialogTitle><DialogDescription>现实运动提供成长，冒险由你自己决定。</DialogDescription></DialogHeader><div className='help-grid'><article><span>01</span><h3>运动结算</h3><p>每分钟2经验，每条最多80经验；按上海日期每天最多150经验、2枚符石。这是游戏奖励规则，不是身体能力评分。</p></article><article><span>02</span><h3>自由成长</h3><p>每次升级获得2点属性。力量提高攻击，耐力增加生命，敏捷提高暴击。所有运动类型享有相同经验规则。</p></article><article><span>03</span><h3>观察再出手</h3><p>攻击回能，重击耗能并穿甲。敌人每三回合的蓄力攻击适合防御。药水恢复45%生命，也会占用一个回合。</p></article><article><span>04</span><h3>休息也能继续</h3><p>营地随时补满药水，每天首次补给领10金币。战败保留成长。首次通关掉落奖励，重打不重复发放。</p></article></div><div className='help-note'><Shield/><p>此版是个人试用：手表先同步到运动平台，再由本游戏读取。当前支持个人 Intervals.icu API Key 或CSV/JSON导入；佳明与苹果健康直连尚未接入。</p></div></DialogContent></Dialog>
  <Dialog open={recordsOpen} onOpenChange={setRecordsOpen}><DialogContent className='game-dialog'><DialogHeader><DialogTitle>运动记录 · {s.records.length} 条</DialogTitle><DialogDescription>日期按上海时间显示。奖励结算会自动保存。</DialogDescription></DialogHeader><div className='all-record-list'>{s.records.map(renderRecord)}</div></DialogContent></Dialog>
 </div>;
}
function Keyboard({onMove,enabled}:{onMove:(move:Move)=>void;enabled:boolean}){const callback=useRef(onMove);callback.current=onMove;useEffect(()=>{if(!enabled)return;const listener=(e:KeyboardEvent)=>{if(e.repeat||e.ctrlKey||e.metaKey||e.altKey||/INPUT|TEXTAREA|SELECT/.test((e.target as HTMLElement)?.tagName)||((e.target as HTMLElement)?.isContentEditable))return;const moves:Record<string,Move>={'1':'attack','2':'heavy','3':'guard','4':'potion'};if(moves[e.key]){e.preventDefault();callback.current(moves[e.key]);}};window.addEventListener('keydown',listener);return()=>window.removeEventListener('keydown',listener);},[enabled]);return null;}
